name: booklist_app
description: A Flutter application for managing your book collection.
version: 1.0.0+1

publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1
  cupertino_icons: ^1.0.6
  path_provider: ^2.1.1
  shared_preferences: ^2.2.2
  image_picker: ^1.0.5
  file_picker: ^6.1.1
  path: ^1.8.3
  uuid: ^4.2.0
  flutter_slidable: ^3.0.1
  cached_network_image: ^3.3.0
  flutter_staggered_grid_view: ^0.6.2
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
